#ifndef IDT_H
#define IDT_H

void idt_error();

void initialize_idt();

enum INTERRUPT_NAMES{
    DIV_BY_ZERO,
    RESERVED,
    NMI_INTERRUPT,
    BREAKPOINT,
    OVERFLOW,
    BOUND_RANGE_EXCEEDED,
    INVALID_OPCODE,
    DEVICE_NOT_AVAILABLE,
    DOUBLE_FAULT,
    COPROCESSOR_SEGMENT_OVERRUN,
    INVALID_TSS,
    SEGMENT_NOT_PRESENT,
    STACK_SEGMENT_FAULT,
    GENERAL_PROTECTION,
    PAGE_FAULT,
    INTEL_RESERVED,
    MATH_FAULT,
    ALIGNMENT_CHECK,
    MACHINE_CKECK,
    SIMD_FLOATING_POINT_EXCEPTION
};
#define NUM_SYSTEM_INTERRUPTS 32

#endif /* IDT_H */
